# Generated by Django 5.1.1 on 2024-10-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_purchase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='representative',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
