# Generated by Django 5.1.1 on 2024-10-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_state_alter_customer_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='state',
        ),
        migrations.AddField(
            model_name='zone',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.city'),
            preserve_default=False,
        ),
    ]
