# Generated by Django 5.1.1 on 2024-10-16 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('customer', '0005_remove_zone_state_zone_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.city'),
        ),
        migrations.RemoveField(
            model_name='zone',
            name='city',
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.state'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.zone'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
