# Generated by Django 5.1.1 on 2024-10-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_address_city_remove_zone_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zone',
            field=models.CharField(max_length=255),
        ),
    ]
