# Generated by Django 5.1.1 on 2024-10-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_address_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='Province',
        ),
    ]
