# Generated by Django 5.1.1 on 2024-10-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attribute_group',
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_group',
            field=models.ManyToManyField(to='product.attributegroup'),
        ),
    ]
