# Generated by Django 5.1.1 on 2024-10-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('customer', '0007_alter_address_zone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
