# Generated by Django 5.1.1 on 2024-10-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_delete_zone'),
        ('customer', '0008_rename_state_address_province'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Province',
        ),
    ]
